services:

  bar-backend:
    build:
      context: ./bar_backend
      args:
        - KEYSTORE_PASSWORD=${PASSWORD}
    restart: always
    container_name: bar-backend
    networks:
      - app_network
    ports:
      - "8080:8080"
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bar_db
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - GBYZZZ_URL_TO_VALIDATE=http://bar-user-enable:8081/validate
      - SPRING_DATA_REDIS_PASSWORD=${PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAPSERVERS=kafka:9093
      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="${PASSWORD}";
      - GBYZZZ_APP_JWT=${JWT_KEY}
      - GBYZZZ_APP_JWT_EXPIRATION=${JWT_EXPIRATION}
      - APP_MINIO_ENDPOINT=http://minio:9000
      - APP_MINIO_USERNAME=${USERNAME}
      - APP_MINIO_PASSWORD=${PASSWORD}
      - APP_MINIO_USERPICBUCKET=user-pic-bucket
      - APP_MINIO_COCKTAILIMAGE=cocktail-image
      - APP_MINIO_COCKTAILTHUMBNAIL=cocktail-thumbnail

  bar-frontend:
    build:
      context: ./bar_frontend
      args:
        - ENV=${ENV}
    container_name: bar-frontend
    restart: always
    networks:
      - app_network
    ports:
      - "3001:3001"


  bar-user-enable:
    build: ./bar_user_enable
    restart: always
    container_name: bar-user-enable
    networks:
      - app_network
    working_dir: /app
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PASSWORD=${PASSWORD}
      - SPRING_KAFKA_BOOTSTRAPSERVERS=kafka:9093
      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="${PASSWORD}";

  bar-email:
    build: ./bar_email
    restart: always
    container_name: bar-email
    networks:
      - app_network
    ports:
      - "8082:8082"
    working_dir: /app
    environment:
      - GBYZZZ_RECOVER_URL=https://localhost:443/recover_password
      - SPRING_MAIL_HOST=${MAIL_HOST}
      - SPRING_MAIL_PORT=${MAIL_PORT}
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAPSERVERS=kafka:9093
      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="${PASSWORD}";

  bar-search:
    build:
      context: ./bar_search
      args:
        - KEYSTORE_PASSWORD=${PASSWORD}
    restart: always
    container_name: bar-search
    networks:
      - app_network
    ports:
      - "8083:8083"
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bar_db?stringtype=unspecified
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PASSWORD=${PASSWORD}
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - SPRING_ELASTICSEARCH_USERNAME=${USERNAME}
      - SPRING_ELASTICSEARCH_PASSWORD=${PASSWORD}
      - SPRING_KAFKA_BOOTSTRAPSERVERS=kafka:9093
      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="${PASSWORD}";
networks:
  app_network:
    external: true
